blank_issues_enabled: false
contact_links:
  - name: Configuration and other support questions
    url: https://github.com/betaflight/betaflight#support-and-developers-channel
    about: Official Slack chat channel and Facebook group about Betaflight
